ci: Update to ubuntu 24, to get newer freetype version.
freetype-sys 0.23 doesn't build with the version shipped in ubuntu 22.
Ubuntu 24 doesn't seem to ship libfreetype-dev in CI images by default.

configuration error in freetype-sys in ubuntu 22.04 CI:
```

  thread 'main' (2233) panicked at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/freetype-sys-0.23.0/build.rs:21:18:
  called `Result::unwrap()` on an `Err` value:
  pkg-config exited with status code 1
  > PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags freetype2 'freetype2 >= 24.3.18'

  pkg-config output:
    Package dependency requirement 'freetype2 >= 24.3.18' could not be satisfied.
    Package 'freetype2' has version '24.1.18', required version is '>= 24.3.18'

  The system library `freetype2` required by crate `freetype-sys` was not found.
  The file `freetype2.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
  The PKG_CONFIG_PATH environment variable is not set.

  HINT: if you have installed the library, try setting PKG_CONFIG_PATH to the directory containing `freetype2.pc`.
```